import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className='flex gap-4 p-4 border-b border-black/[.08] dark:border-white/[.145]'>
          <a href='/' className='hover:underline'>
            Home
          </a>
          <a href='/markers' className='hover:underline'>
            Markers
          </a>
          <a href='/trips' className='hover:underline'>
            Trips
          </a>
          <a href='/3d' className='hover:underline'>
            3D
          </a>
        </nav>
        {children}
      </body>
    </html>
  )
}
