import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'NYC Taxi Demo',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className='flex gap-4 p-4 border-b border-black/[.08] dark:border-white/[.145]'>
          <Link href='/3d' className='hover:underline'>
            3D
          </Link>
          <Link href='/lights' className='hover:underline'>
            Lights
          </Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
